### PR TITLE
Add QUEST satellite data

### PR DESCRIPTION
**Pull request by thompsonmj**
Satellite data shared by @llhouse2. The .xlsx files with multiple sheets per workbook were split into individual CSV files per sheet.

### CODE REVIEW

**Comment by egrace479** [comment]
The `sat_url`s need to be adjusted to point to the images on GitHub (https://github.com/Imageomics/Andromeda/blob/main/datasets/satelliteData/<img_name>.png).

**Comment by hlapp** [comment]
> The `sat_url`'s need to be adjusted to point to the images on GitHub: https://github.com/Imageomics/Andromeda/blob/main/datasets/satelliteData/<img_name>.png.

That's I think the landing page for the file within version control. If the image is to downloadable at the URL it needs to be the raw URL.

**Comment by thompsonmj** [comment]
Thanks @egrace479 and @hlapp ... updated those URLs. Once this merges to `main`, they should become valid.

**Review by egrace479 — APPROVED** [review]

**Review by johnbradley — APPROVED** [review]
LGTM

**Pull request merged**
