### PR TITLE
Add options to merge satellite data

### PR DESCRIPTION
**Pull request by johnbradley**
Adds two checkboxes to allow users to join RGB and Land coverage satellite data into the iNaturalist observations downloaded.

### CODE REVIEW

**Comment by johnbradley** [comment]
@egrace479 Provided the logic for the UI changes. This is what the screen looks like now:
Screen Shot 2023-07-11 at 1 12 48 PM

**Comment by johnbradley** [comment]
Right now we don't have a URL setup for the Landcover data so users will see the following about landcover data not being supported if they use that checkbox. Here is an example with that message and another warning about overlapping regions:
Screen Shot 2023-07-11 at 1 13 01 PM

After merging this PR I will create an issue to fix the overlapping regions based on the recommendation by @llhouse2 to choose the region who's center is closest.

**Comment by johnbradley** [comment]
Another issue I will open after this PR is to show all columns in the observations list. Currently we only show the known good columns coming from the observations. So the columns from the satellite data are only present in the CSV.

**Review by thompsonmj — APPROVED** [review]
LGTM

**Review by egrace479 — APPROVED** [review]
LGTM

**Pull request merged**
